version: "3.8"

services:
  es02:
    image: elastic/elasticsearch:9.2.4
    container_name: es02
    network_mode: host
    restart: unless-stopped

    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
      cluster.name: "drp-elk"
      node.name: "es02"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    volumes:
      - /opt/elastic/es02/data:/usr/share/elasticsearch/data
      - ./config/es02/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /opt/elastic/es02/certs:/usr/share/elasticsearch/config/certs:ro
      - /opt/elastic/snapshots:/mnt/snapshots

    healthcheck:
      test: ["CMD-SHELL", "curl -k -s https://127.0.0.1:9200/_cluster/health | grep -E 'green|yellow' >/dev/null || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
