cluster.name: drp-elk
node.name: es02

# Option B roles: master-eligible + data + ingest
node.roles: [ master, data, ingest ]

path.repo: ["/mnt/snapshots"]

network.host: 10.10.4.96
http.port: 9200
transport.port: 9300

discovery.seed_hosts: ["10.10.4.94:9300", "10.10.4.96:9300", "10.10.4.97:9300"]
cluster.initial_master_nodes: ["es01", "es02", "es03"]

# Monitoring
xpack.monitoring.collection.enabled: true

# Security
xpack.security.enabled: true

# HTTP TLS
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/es02-http.p12

# Transport TLS
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/es02-transport.p12
  truststore.path: certs/es02-transport.p12
