# Logstash settings

# API / Monitoring endpoint (defaults to 9600)
http.host: "0.0.0.0"
http.port: 9600

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Logs
log.level: info
