version: "3.8"

services:
  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    network_mode: host
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            drp-kafka:
              properties:
                bootstrap.servers: "10.10.4.131:9092,10.10.4.132:9092"

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    network_mode: host
    restart: unless-stopped
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "drp-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "10.10.4.131:9092,10.10.4.132:9092"
